ess-dmsc/daquiri

- source/gui/daq/ConsumerDialog.cpp
- source/gui/daq/ConsumerDialog.h
- source/gui/daq/ConsumerDialog.ui
> expand tree button for consumer; updated #141

- source/core/plugin/setting.cpp
- source/core/plugin/setting_metadata.cpp
- source/core/plugin/setting_metadata.h
- tests/core/plugin/setting_metadata.cpp
> "more convenience functions and tests for SettingMeta; updates #149"

- conanfile.txt
- source/consumers/histogram_2d.cpp
- source/consumers/image_2d.cpp
- source/consumers/spectrum_time.cpp
- source/consumers/tof_val_2d.cpp
- source/gui/daq/Consumer2D.cpp
- source/gui/daq/Consumer2D.h
> "flip-y saved in histogram config, with gui integration; updates #120"

- source/consumers/prebinned_1d.cpp
- source/consumers/prebinned_1d.h
> "downsampling for prebinned 1d; updates #158"

- source/gui/daq/ListModeForm.cpp
> "fixed bug of traces not displaying in list mode; updates #162"

- source/gui/SettingsForm.cpp
- source/gui/SettingsForm.h
- source/gui/daq/ConsumerDialog.cpp
- source/gui/daq/ConsumerDialog.h
- source/gui/daq/ConsumerTemplatesForm.cpp
- source/gui/daq/ProjectForm.cpp
- source/gui/widgets/SettingDelegate.cpp
- source/gui/widgets/SettingDelegate.h
- source/producers/DummyDevice/DummyDevice.cpp
> "better file dialogs; updates #176"

- source/gui/main.cpp
- utils/first_build.sh
Changes to first_build script needed to succesfully install essdaq in container
---
> manual conan commands for docker build

- Jenkinsfile
- source/producers/ESSStream/ESSStream.cpp
- source/producers/ESSStream/ESSStream.h
- source/producers/ESSStream/KafkaPlugin.h
- source/producers/ESSStream/ev42_parser.cpp
- source/producers/ESSStream/ev42_parser.h
- source/producers/ESSStream/f142_parser.cpp
- source/producers/ESSStream/f142_parser.h
- source/producers/ESSStream/fb_parser.h
- source/producers/ESSStream/mo01_parser.cpp
- source/producers/ESSStream/mo01_parser.h
> "fb id checks; updates #170"

- source/gui/daq/Consumer1D.cpp
- source/gui/daq/ConsumerMulti1D.cpp
- source/gui/daq/ConsumerTemplatesForm.cpp
- source/gui/daq/ConsumerTemplatesForm.ui
> "done; updates #205"

- Jenkinsfile
- conanfile.txt
- source/core/util/color_bash.h
- source/core/util/lexical_extensions.h
- tests/gtest_color_print.h
Change to use the Jenkins shared library in Jenkinsfile.
Reviewer should check everything looks as normal on Jenkins, including that coverage report is successfully generated.
---
> Modernise Jenkinsfile

- CMakeLists.txt
- Jenkinsfile
Issue 226 (fix macOS build).
---
> Issue 226 replace skip rpath

- source/producers/ESSStream/KafkaPlugin.cpp
- source/producers/ESSStream/KafkaPlugin.h
- utils/daquiri.sh
> Issue 224 broker from env

- source/consumers/spectrum.cpp
- source/gui/daq/Consumer1D.cpp
> add support for custom x-axis labels

- conanfile.txt
> Bump librdkafka version in conanfile

- source/daqlite/CMakeLists.txt
- source/daqlite/Custom2DPlot.cpp
- source/daqlite/ESSConsumer.h
- source/daqlite/MainWindow.cpp
- source/daqlite/MainWindow.h
- source/daqlite/MainWindow.ui
- source/daqlite/WorkerThread.cpp
- source/daqlite/WorkerThread.h
- source/daqlite/daqlite.cpp
- source/gui/daq/ProjectForm.cpp
- source/gui/daq/ProjectForm.h
- source/gui/daq/ProjectForm.ui
- source/gui/daq/ProjectView.cpp
- source/gui/daq/ProjectView.h
> Issue 219 count rates

- source/daqlite/Configuration.cpp
- source/daqlite/Configuration.h
- source/daqlite/Custom2DPlot.cpp
- source/daqlite/Custom2DPlot.h
- source/daqlite/ESSConsumer.cpp
- source/daqlite/MainWindow.cpp
- source/daqlite/MainWindow.h
- source/daqlite/configs/vipcspec2d.json
- source/daqlite/configs/vipcspec3d.json
- source/daqlite/configs/vipfreia.json
- source/daqlite/configs/vipnmx.json
Changes are local to daqlite and does not affect the original and one and only Daquiri.
Added configuration options for log scale on histograms and specifying the color gradient 
fixed a off by one bug when checking for max pixel value.
Added support for 3D detectors which automatically are shown as three projections
a small optimisation to check for zero counts in histogram before calling QtCustomPlot function.
---
> vip demo fixups

- source/daqlite/Custom2DPlot.cpp
- source/daqlite/Custom2DPlot.h
- source/daqlite/MainWindow.cpp
- source/daqlite/MainWindow.h
- source/daqlite/MainWindow.ui
- source/daqlite/configs/viploki.json
> add clear button and fix periodic clear

- source/daqlite/Custom2DPlot.cpp
- source/daqlite/Custom2DPlot.h
- source/daqlite/MainWindow.cpp
- source/daqlite/MainWindow.h
- source/daqlite/MainWindow.ui
- source/daqlite/configs/dreamoffice.json
- source/daqlite/configs/dreamvip.json
- source/daqlite/configs/lokioffice.json
> added dynamic plot buttons

- source/daqlite/Custom2DPlot.cpp
- source/daqlite/Custom2DPlot.h
- source/daqlite/MainWindow.cpp
- source/daqlite/MainWindow.ui
- source/daqlite/configs/amor.json
> Ecdc 2539 daquiri resize refresh

- source/daqlite/Custom2DPlot.cpp
- source/daqlite/Custom2DPlot.h
> mouse over plots coordinates

- source/daqlite/CMakeLists.txt
- source/daqlite/Configuration.cpp
- source/daqlite/Configuration.h
- source/daqlite/CustomTofPlot.cpp
- source/daqlite/CustomTofPlot.h
- source/daqlite/ESSConsumer.cpp
- source/daqlite/ESSConsumer.h
- source/daqlite/MainWindow.cpp
- source/daqlite/MainWindow.h
- source/daqlite/WorkerThread.cpp
- source/daqlite/configs/viploki4amp.json
- source/daqlite/configs/viplokitof.json
> added tof plot functionality

- source/daqlite/Configuration.cpp
- source/daqlite/configs/vipfreiatof.json
> better exception handling for json parsing

- source/daqlite/Configuration.cpp
- source/daqlite/Configuration.h
- source/daqlite/ESSConsumer.cpp
- source/daqlite/ESSConsumer.h
- source/daqlite/MainWindow.cpp
- source/daqlite/WorkerThread.cpp
- source/daqlite/WorkerThread.h
- source/daqlite/configs/amor.json
- source/daqlite/configs/dreamoffice.json
- source/daqlite/configs/lokioffice.json
- source/daqlite/configs/vipcspec2d.json
- source/daqlite/configs/vipcspec3d.json
- source/daqlite/configs/vipdream.json
- source/daqlite/configs/vipfreia.json
- source/daqlite/configs/vipfreiatof.json
- source/daqlite/configs/viploki.json
- source/daqlite/configs/viploki4amp.json
- source/daqlite/configs/viplokitof.json
- source/daqlite/configs/vipnmx.json
- source/daqlite/daqlite.cpp
1) add mutex to protect histogram data
2) add window and plot title
3) add overhead to allocation to prevent crash
4) remove unused variable
5) dos2unix on daquiri.cpp
> Issue 249 mutex

- data/profiles/mgcncs/profile.set
- data/profiles/mgmesytec/profile.set
- data/profiles/nmx/profile.set
- data/profiles/skadi/profile.set
- source/daqlite/Configuration.h
- source/daqlite/configs/amor.json
- source/daqlite/configs/dreamoffice.json
- source/daqlite/configs/lokioffice.json
- source/daqlite/configs/vipcspec2d.json
- source/daqlite/configs/vipcspec3d.json
- source/daqlite/configs/vipdream.json
- source/daqlite/configs/vipfreia.json
- source/daqlite/configs/vipfreiatof.json
- source/daqlite/configs/viploki.json
- source/daqlite/configs/viploki4amp.json
- source/daqlite/configs/viplokitof.json
- source/daqlite/configs/vipnmx.json
> Ecdc 2630 rename efu topics

- source/daqlite/Configuration.cpp
- source/daqlite/Configuration.h
- source/daqlite/CustomTofPlot.cpp
- source/daqlite/MainWindow.cpp
- source/daqlite/MainWindow.h
- source/daqlite/MainWindow.ui
> Updated to autoscale X & Y independently of one another

- source/daqlite/CMakeLists.txt
- source/daqlite/Configuration.h
- source/daqlite/Custom2DPlot.h
- source/daqlite/Custom2DTOFPlot.cpp
- source/daqlite/Custom2DTOFPlot.h
- source/daqlite/CustomAMOR2DTOFPlot.cpp
- source/daqlite/CustomAMOR2DTOFPlot.h
- source/daqlite/ESSConsumer.cpp
- source/daqlite/ESSConsumer.h
- source/daqlite/MainWindow.cpp
- source/daqlite/MainWindow.h
- source/daqlite/WorkerThread.cpp
- source/daqlite/configs/amorb/amormon.json
- source/daqlite/configs/amorb/amortof.json
- source/daqlite/configs/amorb/amortof2d.json
- source/daqlite/daqlite.cpp
- source/daqlite/scripts/amor.bash
- source/daqlite/scripts/amorb.bash
> Issue 263 2 d tof

- Jenkinsfile
> Ecdc 3124 update build to gcc11

- conanfile.txt
- documentation/manual_building.md
> ECDC-3284: Replace Conan Artifactory
